system:
  service_addr: http://127.0.0.1:8082
route-guide:
  service_addr: 127.0.0.1:10000
  server_host_override: x.test.youtube.com
frontend:
  listen_addr:
  port: 8080
book:
  service_addr: 127.0.0.1:8086
  server_host_override: x.test.youtube.com
