apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookservice
spec:
  selector:
    matchLabels:
      app: bookservice
  template:
    metadata:
      labels:
        app: bookservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: bookservice
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        # - name: DISABLE_STATS
        #   value: "1"
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: DISABLE_PROFILER
        #   value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
#        readinessProbe:
#          exec:
#            command: ["/bin/grpc_health_probe", "-addr=:3550"]
#        livenessProbe:
#          exec:
#            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bookservice
spec:
  type: ClusterIP
  selector:
    app: bookservice
  ports:
  - name: grpc
    port: 4000
    targetPort: 4000
