apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
#      annotations:
#        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: server
          image: frontend
          ports:
          - containerPort: 8080
##          readinessProbe:
##            initialDelaySeconds: 10
##            httpGet:
##              path: "/_healthz"
##              port: 8080
##              httpHeaders:
##              - name: "Cookie"
##                value: "shop_session-id=x-readiness-probe"
#          livenessProbe:
#            initialDelaySeconds: 10
#            httpGet:
#              path: "/_healthz"
#              port: 8080
#              httpHeaders:
#              - name: "Cookie"
#                value: "shop_session-id=x-liveness-probe"
          env:
          - name: PORT
            value: "8080"
          - name: SYSTEM_SERVICE_ADDR
            value: "http://systemservice:3550"
          - name: ENV_PLATFORM
            value: "gcp"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
