book:
  service_addr:
  port: 4000 # The server's port
  server_host_override: x.test.youtube.com
  tls: false # Connection uses TLS if true, else plain TCP
  cert_file: # The TLS cert file
  key_file:  # The TLS key file
  json_feature_file: # A json file containing a list of features
